-- ShowCockpit LUA Script: Populate MIDI Remotes
--   created on ShowCockpit v2.15.2
--   by Ricardo Dias
--   on 15-11-2018

cmds = {
	"Assign Remote 2.1 /name=\"Key 0\" /type=hardkey /keycode=\"0\" /note=1 /channel=1",
	"Assign Remote 2.2 /name=\"Key 1\" /type=hardkey /keycode=\"1\" /note=2 /channel=1",
	"Assign Remote 2.3 /name=\"Key 2\" /type=hardkey /keycode=\"2\" /note=3 /channel=1",
	"Assign Remote 2.4 /name=\"Key 3\" /type=hardkey /keycode=\"3\" /note=4 /channel=1",
	"Assign Remote 2.5 /name=\"Key 4\" /type=hardkey /keycode=\"4\" /note=5 /channel=1",
	"Assign Remote 2.6 /name=\"Key 5\" /type=hardkey /keycode=\"5\" /note=6 /channel=1",
	"Assign Remote 2.7 /name=\"Key 6\" /type=hardkey /keycode=\"6\" /note=7 /channel=1",
	"Assign Remote 2.8 /name=\"Key 7\" /type=hardkey /keycode=\"7\" /note=8 /channel=1",
	"Assign Remote 2.9 /name=\"Key 8\" /type=hardkey /keycode=\"8\" /note=9 /channel=1",
	"Assign Remote 2.10 /name=\"Key 9\" /type=hardkey /keycode=\"9\" /note=10 /channel=1",
	"Assign Remote 2.11 /name=\"Please\" /type=hardkey /keycode=\"ENTER\" /note=11 /channel=1",
	"Assign Remote 2.12 /name=\"MA\" /type=hardkey /keycode=\"MA\" /note=12 /channel=1",
	"Assign Remote 2.13 /name=\"Dot\" /type=hardkey /keycode=\"DOT\" /note=13 /channel=1",
	"Assign Remote 2.14 /name=\"Plus\" /type=hardkey /keycode=\"PLUS\" /note=14 /channel=1",
	"Assign Remote 2.15 /name=\"Minus\" /type=hardkey /keycode=\"MINUS\" /note=15 /channel=1",
	"Assign Remote 2.16 /name=\"Thru\" /type=hardkey /keycode=\"THRU\" /note=16 /channel=1",
	"Assign Remote 2.17 /name=\"At\" /type=hardkey /keycode=\"AT\" /note=17 /channel=1",
	"Assign Remote 2.18 /name=\"If\" /type=hardkey /keycode=\"IF\" /note=18 /channel=1",
	"Assign Remote 2.19 /name=\"Full\" /type=hardkey /keycode=\"FULL\" /note=19 /channel=1",
	"Assign Remote 2.20 /name=\"Highlight\" /type=hardkey /keycode=\"HIGH\" /note=20 /channel=1",
	"Assign Remote 2.21 /name=\"Solo\" /type=hardkey /keycode=\"SOLO\" /note=21 /channel=1",
	"Assign Remote 2.22 /name=\"Up\" /type=hardkey /keycode=\"UP\" /note=22 /channel=1",
	"Assign Remote 2.23 /name=\"Down\" /type=hardkey /keycode=\"DOWN\" /note=23 /channel=1",
	"Assign Remote 2.24 /name=\"Prev\" /type=hardkey /keycode=\"PREV\" /note=24 /channel=1",
	"Assign Remote 2.25 /name=\"Next\" /type=hardkey /keycode=\"NEXT\" /note=25 /channel=1",
	"Assign Remote 2.26 /name=\"Set\" /type=hardkey /keycode=\"SET\" /note=26 /channel=1",
	"Assign Remote 2.27 /name=\"U1\" /type=hardkey /keycode=\"U1\" /note=27 /channel=1",
	"Assign Remote 2.28 /name=\"U2\" /type=hardkey /keycode=\"U2\" /note=28 /channel=1",
	"Assign Remote 2.29 /name=\"U3\" /type=hardkey /keycode=\"U3\" /note=29 /channel=1",
	"Assign Remote 2.30 /name=\"U4\" /type=hardkey /keycode=\"U4\" /note=30 /channel=1",
	"Assign Remote 2.31 /name=\"Background\" /type=hardkey /keycode=\"BACKGROUND\" /note=31 /channel=1",
	"Assign Remote 2.32 /name=\"User 1\" /type=hardkey /keycode=\"USER1\" /note=32 /channel=1",
	"Assign Remote 2.33 /name=\"User 2\" /type=hardkey /keycode=\"USER2\" /note=33 /channel=1",
	"Assign Remote 2.34 /name=\"List\" /type=hardkey /keycode=\"LIST\" /note=34 /channel=1",
	"Assign Remote 2.35 /name=\"Blind\" /type=hardkey /keycode=\"BLIND\" /note=35 /channel=1",
	"Assign Remote 2.36 /name=\"Freeze\" /type=hardkey /keycode=\"FREEZE\" /note=36 /channel=1",
	"Assign Remote 2.37 /name=\"Preview\" /type=hardkey /keycode=\"PREVIEW\" /note=37 /channel=1",
	"Assign Remote 2.38 /name=\"Fix\" /type=hardkey /keycode=\"FIX\" /note=38 /channel=1",
	"Assign Remote 2.39 /name=\"Select\" /type=hardkey /keycode=\"SELECT\" /note=39 /channel=1",
	"Assign Remote 2.40 /name=\"Off\" /type=hardkey /keycode=\"OFF\" /note=40 /channel=1",
	"Assign Remote 2.41 /name=\"Temp\" /type=hardkey /keycode=\"TEMP\" /note=41 /channel=1",
	"Assign Remote 2.42 /name=\"Top\" /type=hardkey /keycode=\"TOP\" /note=42 /channel=1",
	"Assign Remote 2.43 /name=\"On\" /type=hardkey /keycode=\"ON\" /note=43 /channel=1",
	"Assign Remote 2.44 /name=\"Go Minus Fast\" /type=hardkey /keycode=\"GOM_FAST\" /note=44 /channel=1",
	"Assign Remote 2.45 /name=\"Learn\" /type=hardkey /keycode=\"LEARN\" /note=45 /channel=1",
	"Assign Remote 2.46 /name=\"Go Plus Fast\" /type=hardkey /keycode=\"GOP_FAST\" /note=46 /channel=1",
	"Assign Remote 2.47 /name=\"Go Minus\" /type=hardkey /keycode=\"GO_MINUS\" /note=47 /channel=1",
	"Assign Remote 2.48 /name=\"Pause\" /type=hardkey /keycode=\"PAUSE\" /note=48 /channel=1",
	"Assign Remote 2.49 /name=\"Go Plus\" /type=hardkey /keycode=\"GO_PLUS\" /note=49 /channel=1",
	"Assign Remote 2.50 /name=\"Time\" /type=hardkey /keycode=\"TIME\" /note=50 /channel=1",
	"Assign Remote 2.51 /name=\"Esc\" /type=hardkey /keycode=\"ESC\" /note=51 /channel=1",
	"Assign Remote 2.52 /name=\"Edit\" /type=hardkey /keycode=\"EDIT\" /note=52 /channel=1",
	"Assign Remote 2.53 /name=\"Oops\" /type=hardkey /keycode=\"OOPS\" /note=53 /channel=1",
	"Assign Remote 2.54 /name=\"Update\" /type=hardkey /keycode=\"UPDATE\" /note=54 /channel=1",
	"Assign Remote 2.55 /name=\"Clear\" /type=hardkey /keycode=\"CLEAR\" /note=55 /channel=1",
	"Assign Remote 2.56 /name=\"Store\" /type=hardkey /keycode=\"STORE\" /note=56 /channel=1",
	"Assign Remote 2.57 /name=\"Assign\" /type=hardkey /keycode=\"ASSIGN\" /note=57 /channel=1",
	"Assign Remote 2.58 /name=\"Align\" /type=hardkey /keycode=\"ALIGN\" /note=58 /channel=1",
	"Assign Remote 2.59 /name=\"Help\" /type=hardkey /keycode=\"HELP\" /note=59 /channel=1",
	"Assign Remote 2.60 /name=\"View\" /type=hardkey /keycode=\"VIEW\" /note=60 /channel=1",
	"Assign Remote 2.61 /name=\"Effect\" /type=hardkey /keycode=\"EFFECT\" /note=61 /channel=1",
	"Assign Remote 2.62 /name=\"Go To\" /type=hardkey /keycode=\"GOTO\" /note=62 /channel=1",
	"Assign Remote 2.63 /name=\"Page\" /type=hardkey /keycode=\"PAGE\" /note=63 /channel=1",
	"Assign Remote 2.64 /name=\"Macro\" /type=hardkey /keycode=\"MACRO\" /note=64 /channel=1",
	"Assign Remote 2.65 /name=\"Preset\" /type=hardkey /keycode=\"PRESET\" /note=65 /channel=1",
	"Assign Remote 2.66 /name=\"Sequ\" /type=hardkey /keycode=\"SEQU\" /note=66 /channel=1",
	"Assign Remote 2.67 /name=\"Cue\" /type=hardkey /keycode=\"CUE\" /note=67 /channel=1",
	"Assign Remote 2.68 /name=\"Executor\" /type=hardkey /keycode=\"EXECUTOR\" /note=68 /channel=1",
	"Assign Remote 2.69 /name=\"Channel\" /type=hardkey /keycode=\"CHANNEL\" /note=69 /channel=1",
	"Assign Remote 2.70 /name=\"Fixture\" /type=hardkey /keycode=\"FIXTURE\" /note=70 /channel=1",
	"Assign Remote 2.71 /name=\"Group\" /type=hardkey /keycode=\"GROUP\" /note=71 /channel=1",
	"Assign Remote 2.72 /name=\"Delete\" /type=hardkey /keycode=\"DELETE\" /note=72 /channel=1",
	"Assign Remote 2.73 /name=\"Copy\" /type=hardkey /keycode=\"COPY\" /note=73 /channel=1",
	"Assign Remote 2.74 /name=\"Move\" /type=hardkey /keycode=\"MOVE\" /note=74 /channel=1",
	"Assign Remote 2.75 /name=\"Tools\" /type=hardkey /keycode=\"TOOLS\" /note=75 /channel=1",
	"Assign Remote 2.76 /name=\"Setup\" /type=hardkey /keycode=\"SETUP\" /note=76 /channel=1",
	"Assign Remote 2.77 /name=\"Backup\" /type=hardkey /keycode=\"BACKUP\" /note=77 /channel=1",
	"Assign Remote 2.78 /name=\"Blackout\" /type=hardkey /keycode=\"BLACKOUT\" /note=78 /channel=1",
	"Assign Remote 2.79 /name=\"Encoder Button\" /type=hardkey /keycode=\"ENCODER\" /note=79 /channel=1",
	"Assign Remote 2.80 /name=\"V1\" /type=hardkey /keycode=\"V1\" /note=80 /channel=1",
	"Assign Remote 2.81 /name=\"V2\" /type=hardkey /keycode=\"V2\" /note=81 /channel=1",
	"Assign Remote 2.82 /name=\"V3\" /type=hardkey /keycode=\"V3\" /note=82 /channel=1",
	"Assign Remote 2.83 /name=\"V4\" /type=hardkey /keycode=\"V4\" /note=83 /channel=1",
	"Assign Remote 2.84 /name=\"V5\" /type=hardkey /keycode=\"V5\" /note=84 /channel=1",
	"Assign Remote 2.85 /name=\"V6\" /type=hardkey /keycode=\"V6\" /note=85 /channel=1",
	"Assign Remote 2.86 /name=\"V7\" /type=hardkey /keycode=\"V7\" /note=86 /channel=1",
	"Assign Remote 2.87 /name=\"V8\" /type=hardkey /keycode=\"V8\" /note=87 /channel=1",
	"Assign Remote 2.88 /name=\"V9\" /type=hardkey /keycode=\"V9\" /note=88 /channel=1",
	"Assign Remote 2.89 /name=\"V10\" /type=hardkey /keycode=\"V10\" /note=89 /channel=1",
	"Assign Remote 2.90 /name=\"X1\" /type=hardkey /keycode=\"X1\" /note=1 /channel=2",
	"Assign Remote 2.91 /name=\"X2\" /type=hardkey /keycode=\"X2\" /note=2 /channel=2",
	"Assign Remote 2.92 /name=\"X3\" /type=hardkey /keycode=\"X3\" /note=3 /channel=2",
	"Assign Remote 2.93 /name=\"X4\" /type=hardkey /keycode=\"X4\" /note=4 /channel=2",
	"Assign Remote 2.94 /name=\"X5\" /type=hardkey /keycode=\"X5\" /note=5 /channel=2",
	"Assign Remote 2.95 /name=\"X6\" /type=hardkey /keycode=\"X6\" /note=6 /channel=2",
	"Assign Remote 2.96 /name=\"X7\" /type=hardkey /keycode=\"X7\" /note=7 /channel=2",
	"Assign Remote 2.97 /name=\"X8\" /type=hardkey /keycode=\"X8\" /note=8 /channel=2",
	"Assign Remote 2.98 /name=\"X9\" /type=hardkey /keycode=\"X9\" /note=9 /channel=2",
	"Assign Remote 2.99 /name=\"X10\" /type=hardkey /keycode=\"X10\" /note=10 /channel=2",
	"Assign Remote 2.100 /name=\"X11\" /type=hardkey /keycode=\"X11\" /note=11 /channel=2",
	"Assign Remote 2.101 /name=\"X12\" /type=hardkey /keycode=\"X12\" /note=12 /channel=2",
	"Assign Remote 2.102 /name=\"X13\" /type=hardkey /keycode=\"X13\" /note=13 /channel=2",
	"Assign Remote 2.103 /name=\"X14\" /type=hardkey /keycode=\"X14\" /note=14 /channel=2",
	"Assign Remote 2.104 /name=\"X15\" /type=hardkey /keycode=\"X15\" /note=15 /channel=2",
	"Assign Remote 2.105 /name=\"X16\" /type=hardkey /keycode=\"X16\" /note=16 /channel=2",
	"Assign Remote 2.106 /name=\"X17\" /type=hardkey /keycode=\"X17\" /note=17 /channel=2",
	"Assign Remote 2.107 /name=\"X18\" /type=hardkey /keycode=\"X18\" /note=18 /channel=2",
	"Assign Remote 2.108 /name=\"X19\" /type=hardkey /keycode=\"X19\" /note=19 /channel=2",
	"Assign Remote 2.109 /name=\"X20\" /type=hardkey /keycode=\"X20\" /note=20 /channel=2"
}

-- Get 'GrandMA2' element
GrandMA2 = GetElement('GrandMA2')

for k,v in pairs(cmds) do
	print(v)
	GrandMA2.CommandExecute_ButtonClick(v)
	--sleep(0.1)
end